{{- if .Values.include.applicationsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secrets
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end -}}