{{- if .Values.Include.CertificateSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-app.fullname" . }}-letsencrypt-certificate
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
    type: letsencrypt-certificate
  annotations:
    estafette.io/letsencrypt-certificate: "true"
    estafette.io/letsencrypt-certificate-hostnames: "{{.Values.AllHostsJoined}}"
type: Opaque
{{- end -}}