{{- if .Values.Include.IAPSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-app.fullname" . }}-iap-oauth-credentials
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
type: Opaque
data:
  client_id: {{.Values.IapOauthCredentialsClientID}}
  client_secret: {{.Values.IapOauthCredentialsClientSecret}}
{{- end -}}