{{- if .Values.include.iapsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-iap-oauth-credentials
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
type: Opaque
data:
  client_id: {{ .Values.iapoauthcredentialsclientid }}
  client_secret: {{ .Values.iapoauthcredentialsclientsecret }}
{{- end -}}