{{- if .Values.Include.Ingress -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "gke-app.fullname" . }}
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.UseNginxIngress}}
    kubernetes.io/ingress.class: "nginx-office"
    {{- if .Values.UseHTTPS }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    {{- end }}
    nginx.ingress.kubernetes.io/client-body-buffer-size: "{{.Values.NginxIngressClientBodyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.Values.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "{{.Values.NginxIngressProxyBuffersNumber}}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{.Values.NginxIngressProxyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.Values.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.Values.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.Values.NginxIngressProxyReadTimeout}}"
    {{- if .Values.OverrideDefaultWhitelist}}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{.Values.NginxIngressWhitelist}}"
    {{- end}}
    {{- if .Values.SetsNginxIngressLoadBalanceAlgorithm }}
    nginx.ingress.kubernetes.io/load-balance: "{{.Values.NginxIngressLoadBalanceAlgorithm}}"
    {{- end }}
    {{- end}}
    {{- if .Values.UseGCEIngress}}
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "false"
    {{- end}}
    {{- if .Values.UseDNSAnnotationsOnIngress}}  
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "{{.Values.UseCloudflareProxy}}"
    estafette.io/cloudflare-hostnames: "{{.Values.HostsJoined}}"
    {{- end}}
spec:
  tls:
  - hosts:
    {{- range .Values.Hosts}}
    - {{.}}
    {{- end}}
    {{- if .Values.UseCertificateSecret }}
    secretName: {{.Values.CertificateSecretName}}
    {{- else }}
    secretName: {{ include "gke-app.fullname" . }}-letsencrypt-certificate
    {{- end }}
  rules:
  {{- range .Values.Hosts}}
  - host: {{.}}
    http:
      paths:
      - path: {{$.IngressPath}}
        backend:
          serviceName: {{$.Name}}
          {{- if $.HasOpenrestySidecar }}
          servicePort: https
          {{- else }}
          servicePort: web
          {{- end }}
  {{- end}}
{{- end -}}