{{- if .Values.Include.Service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gke-app.fullname" . }}
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.UsePrometheusProbe}}
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "{{.Values.Container.Readiness.Path}}"
    {{- end}}
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    {{- if .Values.UseDNSAnnotationsOnService}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "{{.Values.UseCloudflareProxy}}"
    estafette.io/cloudflare-hostnames: "{{.Values.HostsJoined}}"
    {{- end}}
    {{- if .Values.UseBackendConfigAnnotationOnService}}
    beta.cloud.google.com/backend-config: '{"default": "{{ include "gke-app.fullname" . }}"}'
    {{- end}}
    {{- if .Values.UseNegAnnotationOnService}}
    cloud.google.com/neg: '{"ingress": true}'
    {{- end}}
spec:
  type: {{.Values.ServiceType}}
  {{- if .Values.LimitTrustedIPRanges}}
  loadBalancerSourceRanges:
  {{- range .Values.TrustedIPRanges}}
  - {{.}}
  {{- end}}
  {{- end}}
  ports:
  {{- if .Values.HasOpenrestySidecar }}
  {{- if not .Values.UseESP }}
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  {{- end }}
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  {{- else }}
  - name: web
    port: {{.Values.Container.Port}}
    targetPort: web
    protocol: TCP
  {{- end}}
  {{- range .Values.AdditionalServicePorts}}
  - name: {{ include "gke-app.fullname" . }}
    port: {{.Port}}
    targetPort: {{ include "gke-app.fullname" . }}
    protocol: {{.Protocol}}
  {{- end}}
  selector:
    app: {{.Values.AppLabelSelector}}
{{- end -}}