{{- if .Values.Include.ServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gke-app.fullname" . }}
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
{{- end -}}