{{- if .Values.Include.ServiceAccountSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gke-app.fullname" . }}-gcp-service-account
  labels:
    {{- include "gke-app.labels" . | nindent 4 }}
    type: gcp-service-account
  {{- if not .Values.UseLegacyServiceAccountKey}}
  annotations:
    estafette.io/gcp-service-account: 'true'
    estafette.io/gcp-service-account-name: '{{.Values.GoogleCloudCredentialsAppName}}'
    {{- if .Values.DisableServiceAccountKeyRotation}}
    estafette.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end}}
  {{- end}}
type: Opaque
{{- if .Values.UseLegacyServiceAccountKey}}
data:
  service-account-key.json: {{.Values.LegacyServiceAccountKey}}
{{- end}}
{{- end -}}