apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
    anotherlabel: '{{.ManifestData.property3}}'
  annotations:
    {{- if .UsePrometheusProbe}}
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "{{.Container.Readiness.Path}}"
    {{- end}}
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    {{- if .UseDNSAnnotationsOnService}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{.HostsJoined}}"
    {{- end}}
spec:
  type: {{.ServiceType}}
  {{- if .LimitTrustedIPRanges}}
  loadBalancerSourceRanges:
  {{- range .TrustedIPRanges}}
  - {{.}}
  {{- end}}
  {{- end}}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: {{.AppLabelSelector}}