{{- $root := . -}}
{{- range .Services }}
--
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{ $root.Namespace}}
  labels:
    {{- range $key, $value := $root.Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
    anotherlabel: {{$root.ManifestData.property3}}
  annotations:
    {{- if $root.UsePrometheusProbe}}
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "{{$root.Container.Readiness.Path}}"
    {{- end}}
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    {{- if .UseDNSAnnotationsOnService}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{ $root.HostsJoined}}"
    {{- end}}
spec:
  type: {{.ServiceType}}
  {{- if .LimitTrustedIPRanges}}
  loadBalancerSourceRanges:
  {{- range $root.TrustedIPRanges}}
  - {{.}}
  {{- end}}
  {{- end}}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: {{ $root.AppLabelSelector}}
{{- end}}