apiVersion: v1
kind: Service
metadata:
  name: {{ include "gke-app.fullname" . }}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
    anotherlabel: {{.Values.ManifestData.property3}}
  annotations:
    {{- if .Values.UsePrometheusProbe}}
    prometheus.io/probe: "true"
    prometheus.io/probe-path: "{{.Values.Container.Readiness.Path}}"
    {{- end}}
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    {{- if .Values.UseDNSAnnotationsOnService}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "true"
    estafette.io/cloudflare-hostnames: "{{.Values.HostsJoined}}"
    {{- end}}
spec:
  type: {{.Values.ServiceType}}
  {{- if .Values.LimitTrustedIPRanges}}
  loadBalancerSourceRanges:
  {{- range .Values.TrustedIPRanges}}
  - {{.}}
  {{- end}}
  {{- end}}
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: {{.Values.AppLabelSelector}}