{{- if .Values.include.backendconfig -}}
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: {{ .Values.name }}
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: {{ .Values.name }}-iap-oauth-credentials
  timeoutSec: {{ .Values.backendconfigtimeout }}
{{- end -}}