{{- if .Values.include.poddisruptionbudget -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.name }}
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.applabelselector }}
      {{- if .Values.includetracklabel }}
      track: {{ .Values.tracklabel }}
      {{- end }}
  maxUnavailable: 1
{{- end -}}