{{- if .Values.include.serviceheadless -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-node
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: web
    port: {{ .Values.container.port }}
    targetPort: web
    protocol: TCP
  {{- range .Values.additionalserviceports }}
  - name: {{ .Values.name }}
    port: {{ .port }}
    targetPort: {{ .Values.name }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ .Values.applabelselector }}
{{- end -}}