{{- if .Values.include.serviceaccountsecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-gcp-service-account
  labels:
    {{- range $key, $value := .Values.labels}}
    {{$key}}: {{$value}}
    {{- end}}
    type: gcp-service-account
  {{- if not .Values.uselegacyserviceaccountkey }}
  annotations:
    estafette.io/gcp-service-account: 'true'
    estafette.io/gcp-service-account-name: '{{ .Values.googlecloudcredentialsappname }}'
    {{- if .Values.disableserviceaccountkeyrotation }}
    estafette.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end }}
  {{- end }}
type: Opaque
{{- if .Values.uselegacyserviceaccountkey }}
data:
  service-account-key.json: {{ .Values.legacyserviceaccountkey }}
{{- end }}
{{- end -}}