apiVersion: v1
kind: Secret
metadata:
  name: {{.NameWithTrack}}-secrets
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
    type: application
type: Opaque
data:
  {{- range $key, $value := .Secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
  {{- range $key, $value := .Container.SecretEnvironmentVariables }}
  {{ $key }}: {{ $value | b64enc}}
  {{- end }}