apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  {{- if .UseHpaScaler}}
  annotations:
    estafette.io/hpa-scaler: "true"
    estafette.io/hpa-scaler-prometheus-query: "{{.HpaScalerPromQuery}}"
    estafette.io/hpa-scaler-requests-per-replica: "{{.HpaScalerRequestsPerReplica}}"
    estafette.io/hpa-scaler-delta: "{{.HpaScalerDelta}}"
    estafette.io/hpa-scaler-scale-down-max-ratio: "{{.HpaScalerScaleDownMaxRatio}}"
  {{- end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.NameWithTrack}}
  {{- if eq .TrackLabel "canary" }}
  minReplicas: {{.Canary.MinReplicas}}
  {{- else }}
  minReplicas: {{.MinReplicas}}
  {{- end }}
  {{- if eq .TrackLabel "canary" }}
  maxReplicas: {{.Canary.MaxReplicas}}
  {{- else }}
  maxReplicas: {{.MaxReplicas}}
  {{- end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{.TargetCPUPercentage}}
  {{- if .HpaBehavior}}
  behavior:
{{(call $.ToYAML .HpaBehavior) | indent 4}}
  {{- end}}