apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
  {{- if .UseHpaScaler}}
  annotations:
    estafette.io/hpa-scaler: "true"
    estafette.io/hpa-scaler-prometheus-query: "{{.HpaScalerPromQuery}}"
    estafette.io/hpa-scaler-requests-per-replica: "{{.HpaScalerRequestsPerReplica}}"
    estafette.io/hpa-scaler-delta: "{{.HpaScalerDelta}}"
    estafette.io/hpa-scaler-scale-down-max-ratio: "{{.HpaScalerScaleDownMaxRatio}}"
  {{- end}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.NameWithTrack}}
  minReplicas: {{.MinReplicas}}
  maxReplicas: {{.MaxReplicas}}
  targetCPUUtilizationPercentage: {{.TargetCPUPercentage}}