apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-iap-oauth-credentials
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key | quote}}: {{$value | quote}}
    {{- end}}
type: Opaque
data:
  client_id: {{.IapOauthCredentialsClientID}}
  client_secret: {{.IapOauthCredentialsClientSecret}}