apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-image-pull-secret
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
    type: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{.DockerConfig | toJson | b64enc | quote }}