apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    {{- if .UseNginxIngress}}
    {{- if .UseHTTPS }}
    nginx.ingress.kubernetes.io/backend-protocol: "{{.NginxIngressBackendProtocol}}"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    {{- end }}
    {{- if .AllowHTTP }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    {{- end}}
    nginx.ingress.kubernetes.io/client-body-buffer-size: "{{.NginxIngressClientBodyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "{{.NginxIngressProxyBuffersNumber}}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{.NginxIngressProxyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.NginxIngressProxyReadTimeout}}"
    {{- if .OverrideDefaultWhitelist}}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{.NginxIngressWhitelist}}"
    {{- end}}
    {{- if .SetsNginxIngressLoadBalanceAlgorithm }}
    nginx.ingress.kubernetes.io/load-balance: "{{.NginxIngressLoadBalanceAlgorithm}}"
    {{- end }}
    {{- end}}
    {{- if .UseGCEIngress}}
    kubernetes.io/ingress.allow-http: "false"
    {{- end}}
    {{- if .UseDNSAnnotationsOnIngress}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "{{.UseCloudflareProxy}}"
    estafette.io/cloudflare-hostnames: "{{.HostsJoined}}"
    {{- end}}
spec:
  {{- if .UseNginxIngress }}
  ingressClassName: nginx-office
  {{- end }}
  {{- if .UseGCEIngress}}
  ingressClassName: gce
  {{- end }}
  tls:
  - hosts:
    {{- range .Hosts}}
    - {{.}}
    {{- end}}
    {{- if .UseCertificateSecret }}
    secretName: {{.CertificateSecretName}}
    {{- else }}
    secretName: {{.Name}}-letsencrypt-certificate
    {{- end }}
  rules:
  {{- range .Hosts}}
  - host: {{.}}
    http:
      paths:
      - path: {{$.IngressPath}}
        pathType: {{$.PathType}}
        backend:
          service:
            name: {{$.Name}}
            port:
              {{- if $.HasOpenrestySidecar }}
              name: https
              {{- else }}
              name: web
              {{- end }}
  {{- end}}
