apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if eq .TrackLabel "canary" }}
  name: {{.NameWithTrack}}
  {{- else }}
  name: {{.Name}}
  {{- end }}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "{{.NginxIngressBackendProtocol}}"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "on"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "{{.NginxIngressClientBodyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-body-size: "{{.NginxIngressProxyBodySize}}"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "{{.NginxIngressProxyBuffersNumber}}"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "{{.NginxIngressProxyBufferSize}}"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "{{.NginxIngressProxyConnectTimeout}}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{.NginxIngressProxySendTimeout}}"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{.NginxIngressProxyReadTimeout}}"
    {{- if .UseCloudflareEstafetteExtension}}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: "{{.UseCloudflareProxy}}"
    estafette.io/cloudflare-hostnames: "{{.HostsJoined}}"
    {{- end }}
    {{- if .UseExternalDNS }}
    external-dns.alpha.kubernetes.io/enabled: "true"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "{{.UseCloudflareProxy}}"
    {{- end }}
    {{- if eq .TrackLabel "canary" }}
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "{{ .Canary.Header }}"
    nginx.ingress.kubernetes.io/canary-by-header-value: "{{ .Canary.HeaderValue }}"
    nginx.ingress.kubernetes.io/canary-weight: "{{ .Canary.Weight}}"
    {{- end}}
    {{- if .NginxIngressConfigurationSnippet }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{ .NginxIngressConfigurationSnippet | indent 6 }}
    {{- else }}
spec:
  ingressClassName: nginx-public
  tls:
  - hosts:
    {{- range .Hosts}}
    - {{.}}
    {{- end}}
    {{- if .UseCertificateSecret }}
    secretName: {{.CertificateSecretName}}
    {{- else }}
    secretName: {{.Name}}-letsencrypt-certificate
    {{- end }}
  rules:
  {{- range .Hosts}}
  - host: {{.}}
    http:
      paths:
      - path: {{$.IngressPath}}
        pathType: {{$.PathType}}
        backend:
          service:
            {{- if $.TrackLabel }}
            name: {{$.Service.Name}}-{{$.TrackLabel}}
            {{- else }}
            name: {{$.Service.Name}}
            {{- end }}
            port:
              name: https
  {{- end}}
