apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key}}: {{$value}}
    {{- end}}
spec:
  selector:
    matchLabels:
      app: {{.AppLabelSelector}}
      {{- if .IncludeTrackLabel}}
      track: {{.TrackLabel}}
      {{- end}}
      {{- if .IncludeReleaseIDSelector }}
      estafette.io/release-id: {{.ReleaseIDSelector}}
      {{- end}}
  maxUnavailable: 1