apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
spec:
  selector:
    matchLabels:
      "app": {{ .AppLabelSelector | quote }}
      {{- if .IncludeTrackLabel}}
      "track": {{ .TrackLabel | quote }}
      {{- end}}
      {{- if .IncludeAtomicIDSelector }}
      "estafette.io/atomic-id": {{ .AtomicID | quote }}
      {{- end}}
  maxUnavailable: 1