apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}-node
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{$key | quote}}: {{$value | quote}}
    {{- end}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
  - name: web
    port: {{.Container.Port}}
    targetPort: web
    protocol: TCP
  {{- range .AdditionalServicePorts}}
  - name: {{.Name}}
    port: {{.Port}}
    targetPort: {{.Name}}
    protocol: {{.Protocol}}
  {{- end}}
  selector:
    app: {{.AppLabelSelector}}