apiVersion: v1
kind: Secret
metadata:
  name: {{.GoogleCloudCredentialsAppName}}-gcp-service-account
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .GoogleCloudCredentialsLabels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
    type: gcp-service-account
  {{- if not .UseLegacyServiceAccountKey}}
  annotations:
    estafette.io/gcp-service-account: 'true'
    estafette.io/gcp-service-account-name: '{{.GoogleCloudCredentialsAppName}}'
    {{- if .DisableServiceAccountKeyRotation}}
    estafette.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end}}
  {{- end}}
type: Opaque
{{- if .UseLegacyServiceAccountKey}}
data:
  service-account-key.json: {{.LegacyServiceAccountKey}}
{{- end}}