---
apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end}}
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"https":"HTTPS"}'
    estafette.io/cloudflare-dns: "true"
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    "app": {{ .AppLabelSelector | quote }}