apiVersion: v1
kind: Secret
metadata:
  name: {{.GoogleCloudCredentialsAppName}}-gcp-service-account
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .GoogleCloudCredentialsLabels}}
    {{$key}}: {{$value}}
    {{- end}}
    type: gcp-service-account
  annotations:
    {{- if not .UseLegacyServiceAccountKey}}
    estafette.io/gcp-service-account: 'true'
    estafette.io/gcp-service-account-name: '{{.GoogleCloudCredentialsAppName}}'
    {{- if .DisableServiceAccountKeyRotation}}
    estafette.io/gcp-service-account-disable-key-rotation: 'true'
    {{- end}}
    {{- end}}
type: Opaque
{{- if .UseLegacyServiceAccountKey}}
  service-account-key.json: {{.LegacyServiceAccountKey}}
{{- end}}