apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{.NameWithTrack}}
  namespace: {{.Namespace}}
  labels:
    {{- range $key, $value := .Labels}}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end}}
spec:
  targetRef:
    apiVersion: apps/v1
    kind:       Deployment
    name: {{.NameWithTrack}}
  updatePolicy:
    updateMode: "{{.VpaUpdateMode}}"